version: '3'

services:
  melody-service:
    build: .
    container_name: melody-service
    mem_limit: 800m
    ports:
      - 80:8080
    env_file:
      - '.env'
    logging:
      driver: json-file