server :
  port : 8080

  tomcat :
    connectionUploadTimeout : 3000
    connectionTimeout : 3000
    connection-timeout : 3000
    max-swallow-size : 20MB
    max-http-form-post-size : 20MB

spring:
  main:
    allow-bean-definition-overriding: true

  servlet :
    multipart :
      max-file-size: 10MB
      max-request-size: 20MB

  application:
    name: melody-server

  profiles :
    active : dev

---
spring.config.activate.on-profile: dev

logging.level.root: debug
logging.level.com.melody.melody: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:melody-db

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa :
    hibernate:
      ddl_auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          max-interval: 5s
          multiplier: 2

rabbit:
  exchange:
    compose-music :
      name: "x.compose-music"
      durable : false
      autoDelete : true

  queue:
    complete-music:
      name: "q.complete-music"
      durable : false
      exclusive : true
      autoDelete : true

  binding:
    - exchange: ${rabbit.exchange.compose-music.name}
      queue: ${rabbit.queue.complete-music.name}
      key: "#"


jasypt:
  encryptor:
    bean: jasyptStringEncryptor

app:
  rest:
    logout:
      redirectUri: http://localhost:3000

  jwt:
    accessToken:
      validMilliSecond: 600000 # 10 * 60 * 1000 # 10분
      secretKey: ENC(9wDOYRXVuhWEhzL7c/yfybEbvhQdsVe1kyn6wIiWUahcleRTM5jm3ulomvreRw1FlbGq+OMIbWA=)
      name: Authorization

    refreshToken:
      validMilliSecond: 1036800000 # 12 * 24 * 60 * 60 * 1000 # 12일
      secretKey: ENC(ZIFmw2pQ8F06AjNOW2XH98hJ0DwQkf7+9VfXCflEsyBZEXCZEYjszZh/J3RgEV96WpGhEEwdWf4=)
      name: rt

aws:
  s3:
    image:
      credentials:
        accessKey: ENC(EodsFXWhMnY1vZc5XkY9rFmLKpgFz4h8gmHvsZrwQOw=)
        secretKey: ENC(AqnKcxmzs3lGMGMTypBODOS/vqiJN26DY1kD54yMbVIY/AWSwycnVoN8Yb+gPmlQPy5iiEQktkw=)
      region: ap-northeast-2
      bucketName: melody-image-bucket
      allowMediaType: image/jpng,image/jpg,image/png

  lambda:
    generateMusic:
      uri: ENC(9LAe9lSFdHVaOIp5iAAYHtD44zs6wIYJslqX5G8bVhFFZ76VgyAiimn2KCOuns+jBVKSzn4jNhKJSnBsdSCaG0ceatRSufT8o1w8Y8nh0wk=)

    emotionClassification:
      uri: ENC(4gFc/D7Ao7Q2s3jq2N5Oak4u8nxwSo77/+j2spO7SpOOyAWvceqHOKCUwS3bOrt50gL7JGZwcuyJ4AVJolmXCjn24UTbrRvj/jDg4Jma8IjmqxSltM+Mgw==)
