server :
  port : 8080

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: melody-server

  profiles :
    active : dev

---
spring.config.activate.on-profile: dev

logging.level.root: debug
logging.level.com.melody.melody: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:melody-db

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa :
    hibernate:
      ddl_auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true


aws:
  credentials:
    accessKey: none
    secretKey: none

  s3:
    image:
      credentials:
        accessKey: ${aws.credentials.accessKey}
        secretKey: ${aws.credentials.secretKey}
      region: ap-northeast-2
      bucketName: none